name: temfpy

channels:
  - defaults
  - conda-forge
  - opensourceeconomics

dependencies:

  - python=3.7
  - sphinx>=1.4
  - pandas>=0.25
  - numpy=1.16
  - scipy
  - jupyter
  - seaborn
  - pytest=5.4.3
  - numba
  - pip=19.3.1
  - pdbpp
  - chaospy
  - pytest-black
  - pytest-flakes
  - pytest-cov
  - pytest-sugar
  - jupyterlab
  - nbsphinx
  - hypothesis
  - patsy
  - estimagic
  - pip:
    - salib==1.3.8
    - isort
    - black
    - black-nb
    - flake8-nb
    - sphinx_rtd_theme
    - nbsphinx
    - sphinxcontrib-bibtex
    - numpydoc
    - pytest-randomly
    - pytest-stress
    - cairosvg
    - sphinxcontrib-svg2pdfconverter[CairoSVG]
