name: temfpy

channels:
  - defaults
  - conda-forge
  - opensourceeconomics

dependencies:
  - python>=3.7
  - pip>=19.3.1
  - sphinx>=1.4
  - sphinx_rtd_theme
  - nbsphinx
  - numpydoc
  - sphinxcontrib-bibtex>=2.0.0
  - pandas>=0.25
  - numpy>=1.16
  - scipy
  - jupyter
  - seaborn
  - pytest>=5.4.3
  - black>=21.0
  - numba
  - pdbpp
  - pre-commit
  - pytest-black
  - pytest-flakes
  - pytest-cov
  - pytest-sugar
  - jupyterlab
  - hypothesis
  - numdifftools

  - pip:
    - isort
    - black-nb
    - flake8-nb
    - pytest-randomly
    - pytest-stress
    - cairosvg
    - sphinxcontrib-svg2pdfconverter[CairoSVG]
