{% set data = load_setup_py_data() %}

package:
  name: temfpy
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  number: 0

requirements:
  build:
    - python
    - setuptools
  host:
    - python

  run:
    - python
    - numpy >=1.16
    - pandas >=1
    - scipy
    - bokeh >=2.0
    - seaborn >=0.10.0

about:
  home: https://github.com/OpenSourceEconomics/temfpy
  license: MIT
  license_family: MIT
  summary: Python package with test functions for various numerical components
