channels:
  - conda-forge

dependencies:
  - python=3.7
  - ipython
  - nbsphinx
  - sphinx
  - jupyter_client
  - numpy
  - pandas
  - scipy
  - seaborn
  - pytest
  - numba
  - chaospy
  - numdifftools
  - sys
  - pip:
    - sphinxcontrib-bibtex
