channels:
  - conda-forge
  - opensourceeconomics

dependencies:
  - python=3.7
  - ipython
  - nbsphinx
  - sphinx
  - jupyter_client
  - numpy
  - pandas
  - scipy
  - seaborn
  - pytest
  - numba
  - chaospy
  - patsy
  - estimagic
  - temfpy
  - pip:
    - sphinxcontrib-bibtex
