name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1.0.2
      with:
           activate-environment: temfpy
           environment-file: environment.yml
           python-version: 3.7
           auto-activate-base: false

    - name: run tests
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        pytest --cov=temfpy --cov-report=xml

        # We want to make sure proper formatting of the notebooks.
        flake8-nb; [ $? -eq 0 ] || exit 1
        black-nb --check .; [ $? -eq 0 ] || exit 1

        # We want to test a simple install.
        conda install -c opensourceeconomics temfpy

    - name: upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: coverage.xml

    - name: run figures
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        source .envrc
        run-figures
